name: HappyWork
options:
  bundleIdPrefix: com.happywork
  deploymentTarget:
    iOS: '17.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    ENABLE_PREVIEWS: YES
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages: {}
targets:
  HappyWork:
    type: application
    platform: iOS
    sources:
      - path: HappyWork
    settings:
      base:
        INFOPLIST_FILE: HappyWork/Info.plist
    dependencies:
      - target: HappyWorkWidget
  HappyWorkWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: HappyWorkWidget
    settings:
      base:
        INFOPLIST_FILE: HappyWorkWidget/Info.plist
        APPLICATION_EXTENSION_API_ONLY: YES
  HappyWorkTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HappyWorkTests
    settings:
      base:
        INFOPLIST_FILE: HappyWorkTests/Info.plist
    dependencies:
      - target: HappyWork
schemes:
  HappyWork:
    build:
      targets:
        HappyWork: [run, test]
        HappyWorkWidget: [run]
    test:
      gatherCoverageData: true
      targets:
        - name: HappyWorkTests
          parallelizable: true
    run:
      config: Debug
